Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "./"
    d.create_args = ["-t","-i"]
    d.cmd = ["/sbin/my_init"]
  end
  #config.ssh.username = "root"
end

